---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
    default_style: "light"
    downcute_theme: "default"
---


```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
```

```{r}
library(data.table)
library(parallel)
```

Unzip the file through R 
```{r}

MyDir <- c("/Users/changenetalexandre/Library/CloudStorage/OneDrive-u-bordeaux.fr/Postdoc_Italy/data/GBIF/test")
setwd(MyDir)
getwd()
list.files()
Myfile <- list.files()[5]
Nlines <- system(paste0("wc -l ",MyDir,Myfile),intern = T)
Nlines <- strsplit(Nlines," ")
Nlines2 <- as.numeric(Nlines[[1]][2])


mystr <- scan("/Users/changenetalexandre/Library/CloudStorage/OneDrive-u-bordeaux.fr/Postdoc_Italy/data/GBIF/0114847-210914110416597.csv",what = "character",sep ="\n",  nlines =1)
strsplit(mystr, "\t")
colstokeep <- c(10,18,17,28,19,20)
mynames<-strsplit(mystr, "\t")[[1]][colstokeep]
mynames

#loop over gbif chunks:
chunks <- 1000
Chunklines <- round(Nlines2/chunks)

# cleaned<-data.table (NA,NA,NA,NA, NA,NA)
# names(cleaned)<-c("species", "longitude", "latitude","date","coordinateuncertaintyinmeters", "coordinateprecision")

N.Chunk <- as.list(1:chunks)
NamesDF <- paste0("dat.GBIF_",1:chunks)
dir.create(path = "/Users/changenetalexandre/Library/CloudStorage/OneDrive-u-bordeaux.fr/Postdoc_Italy/data/GBIF/All.Chunk")
Ncore <- 6

dfM <- fread("~/Library/CloudStorage/OneDrive-u-bordeaux.fr/Postdoc_Italy/data/GBIF/0114847-210914110416597.csv", header = T, sep = "\t", dec = ".", quote = "", data.table = T)

mcmapply(function(x,y){
    mytemp <- fread(paste0(MyDir,Myfile),
                   sep="\t",
                   dec = ".",
                   quote="",
                   blank.lines.skip=TRUE,
                   na.strings = c("", NA),
                   fill=T, 
                   data.table = T, 
                #select =colstokeep,
                nrows = Chunklines,
                skip=(x-1)*Chunklines)
      setwd(paste0(MyDir,"All.Chunk/"))
    saveRDS(mytemp,file = paste0(y,".rds"))},x=N.Chunk,y=NamesDF,mc.cores=Ncore)
rm(list = c("mytemp"))
gc()
getwd()
```


Other solution: Zcat -> envoie dans un fichier, lecture du ficheir, save rds suppression. 

Other solutions: stackoverflow

```{r}
MyDir <- c("/Users/changenetalexandre/Library/CloudStorage/OneDrive-u-bordeaux.fr/Postdoc_Italy/data/GBIF/test/")
setwd(MyDir)
getwd()
list.files()
Myfile <- list.files()[1]
Nlines <- system(paste0("wc -l ",MyDir,Myfile),intern = T)
Nlines <- strsplit(Nlines," ")
Nlines2 <- as.numeric(Nlines[[1]][2])

chunks <- 100
Chunklines <- round(Nlines2/chunks)

# cleaned<-data.table (NA,NA,NA,NA, NA,NA)
# names(cleaned)<-c("species", "longitude", "latitude","date","coordinateuncertaintyinmeters", "coordinateprecision")

N.Chunk <- as.list(1:chunks)
NamesDF <- paste0("dat.GBIF_",1:chunks)
Ncore <- 10
Unzip_Name <- c(unzip(Myfile, list=TRUE)[1]) # obtain the name in the zip

mcmapply(function(x,y){
  data <- read.table(unz(Myfile, Unzip_Name),
                nrows = Chunklines,
                header=T,
                   sep="\t",
                   dec = ".",
                   quote="",
                   blank.lines.skip=TRUE,
                   na.strings = c("", NA),
                   fill=T, 
                skip=(x-1)*Chunklines) 
    saveRDS(data,file = paste0(y,".rds"))},x=N.Chunk,y=NamesDF,mc.cores=Ncore)
rm(list = c("data"))
gc()
getwd()
test <- readRDS(paste0("test/dat.GBIF_11.rds"))


```





Next chunk is meant to select in each rds what we want. 
```{r}
#because we skip the first i rows, we don't know the column names anymore. thats why we
  #need to work with numbers
  names(mytemp) = mynames
  
  mytemp <- mytemp %>%
    # rename columns
    setnames(old = c("decimallongitude", "decimallatitude","year"),
             new = c("longitude", "latitude","date")) %>%
    # clean coordinates
    coord_impossible()%>%
    coord_incomplete()%>%
    coord_unlikely()%>%
    # remove empty cells
    na.omit() %>%
    filter(!(species=="")) %>%
    # temporal filters
    filter(date < as.Date("2022-02-01")) %>%
    filter(date > as.Date("1950-01-01")) %>%
    # remove duplicates
    unique()
  cleaned <- rbind(cleaned, mytemp)
}
fread(cmd = 'unzip -cq GBIF_PLANTS_17_02_2022.zip')



```

